### ISSUE TITLE
GSit Error

### ISSUE THREAD

**Issue by PizzaRules668** [Gecolay/GSit#106]
I am running a Spigot 1.20.1 Server with GSit version 1.4.6. When I right click on a stair or run `/sit` the server throws an error.
Is it something I configured wrong or is a GSit problem?

Error Log
```
[09:16:18] [Server thread/INFO]: Pizzarules668 issued server command: /sit
[09:16:18] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.level.entity.LevelEntityGetterAdapter.addNewEntity(net.minecraft.world.entity.Entity)
[09:16:18] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[09:16:18] [Server thread/WARN]:        at dev.geco.gsit.mcv.v1_20_R1.util.EntityUtil.spawnEntity(EntityUtil.java:90)
[09:16:18] [Server thread/WARN]:        at dev.geco.gsit.mcv.v1_20_R1.util.EntityUtil.createSeatEntity(EntityUtil.java:44)
[09:16:18] [Server thread/WARN]:        at dev.geco.gsit.manager.SitManager.createSeat(SitManager.java:86)
[09:16:18] [Server thread/WARN]:        at dev.geco.gsit.manager.SitManager.createSeat(SitManager.java:56)
[09:16:18] [Server thread/WARN]:        at dev.geco.gsit.cmd.GSitCommand.onCommand(GSitCommand.java:107)
[09:16:18] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[09:16:18] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[09:16:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:871)
[09:16:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50)
[09:16:18] [Server thread/WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265)
[09:16:18] [Server thread/WARN]:        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314)
[09:16:18] [Server thread/WARN]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1922)
[09:16:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67)
[09:16:18] [Server thread/WARN]:        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[09:16:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156)
[09:16:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
[09:16:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124)
[09:16:18] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019)
[09:16:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[09:16:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Gecolay** [comment]
@PizzaRules668 which server version and server type do you use?

**Comment by PizzaRules668** [comment]
I run Spigot 1.20.1

**Comment by Gecolay** [comment]
oh sry i missed that part in the first message

**Comment by PizzaRules668** [comment]
Its all right we all have those days, if there is any other information you need let met know

**Comment by Gecolay** [comment]
Should be fixed with the next update.

**Comment by PizzaRules668** [comment]
Alright
