### ISSUE TITLE
Error when using these commands

### ISSUE THREAD

**Issue by servicomcr** [Gecolay/GSit#109]
Hello, I was testing on my server using Arclight 1.18.2, but I encountered this error when using these commands.

Mi servidor está funcionando en:
Versión: arclight-1.18.2-1.0.7-40114eb5
Fecha de compilación: 2022-10-29 13:52:07
Java: 17

/lay
/bellyflop
/spin 
/crawl

[21:07:09 INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@53297740
[21:07:09 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundChatPacket@42dbd1b9, suppressing error
org.bukkit.command.CommandException: Unhandled exception executing command 'bellyflop' in plugin GSit v1.4.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServerMixin.java:826) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerPlayNetHandlerMixin.java:2595) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerPlayNetHandlerMixin.java:2435) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerPlayNetHandlerMixin.java:2422) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.PacketUtils.md60f2e8$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Byte (java.lang.Integer and java.lang.Byte are in module java.base of loader 'bootstrap')
        at dev.geco.gsit.mcv.v1_18_R2.objects.GPoseSeat.spawn(GPoseSeat.java:133) ~[?:?]
        at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:110) ~[?:?]
        at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:62) ~[?:?]
        at dev.geco.gsit.cmd.GBellyFlopCommand.onCommand(GBellyFlopCommand.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        ... 21 more

**Comment by servicomcr** [comment]
[27Jun2023 21:07:09.323] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: roshitocr issued server command: /bellyflop
[27Jun2023 21:07:09.326] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@53297740
[27Jun2023 21:07:09.330] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundChatPacket@42dbd1b9, suppressing error
org.bukkit.command.CommandException: Unhandled exception executing command 'bellyflop' in plugin GSit v1.4.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5] {re:classloading,re:mixin}
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5] {re:mixin,re:classloading}
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServerMixin.java:826) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,re:mixin,re:mixin}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerPlayNetHandlerMixin.java:2595) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerPlayNetHandlerMixin.java:2435) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerPlayNetHandlerMixin.java:2422) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:network.ServerPlayNetHandlerMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.arclight.impl.forge.optimization.json:network.ServerGamePacketListenerImplMixin_Optimize,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CChatMessagePacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.game.CChatMessagePacketMixin,pl:mixin:A}
	at net.minecraft.network.protocol.PacketUtils.md60f2e8$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.core.json:network.protocol.PacketThreadUtilMixin,pl:mixin:A}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin}
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Byte (java.lang.Integer and java.lang.Byte are in module java.base of loader 'bootstrap')
	at dev.geco.gsit.mcv.v1_18_R2.objects.GPoseSeat.spawn(GPoseSeat.java:133) ~[?:?] {}
	at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:110) ~[?:?] {}
	at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:62) ~[?:?] {}
	at dev.geco.gsit.cmd.GBellyFlopCommand.onCommand(GBellyFlopCommand.java:114) ~[?:?] {}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5] {re:classloading,re:mixin}
	... 21 more

**Comment by servicomcr** [comment]
[21:57:52 INFO]: AxelCristal issued server command: /spin
[21:57:52 INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@1b3b7183
[21:57:52 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundChatPacket@50aef02e, suppressing error
org.bukkit.command.CommandException: Unhandled exception executing command 'spin' in plugin GSit v1.4.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServerMixin.java:826) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9957_(ServerPlayNetHandlerMixin.java:2595) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerPlayNetHandlerMixin.java:2435) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7388_(ServerPlayNetHandlerMixin.java:2422) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.m_5797_(CChatMessagePacketMixin.java:7) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.network.protocol.PacketUtils.mdace812$lambda$ensureRunningOnSameThread$0$0(PacketThreadUtilMixin.java:537) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:799) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServerMixin.java:164) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServerMixin.java:782) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServerMixin.java:776) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServerMixin.java:762) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2139) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23109!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Byte (java.lang.Integer and java.lang.Byte are in module java.base of loader 'bootstrap')
        at dev.geco.gsit.mcv.v1_18_R2.objects.GPoseSeat.spawn(GPoseSeat.java:133) ~[?:?]
        at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:110) ~[?:?]
        at dev.geco.gsit.manager.PoseManager.createPose(PoseManager.java:62) ~[?:?]
        at dev.geco.gsit.cmd.GSpinCommand.onCommand(GSpinCommand.java:114) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight-1.18.2-1.0.7-40114eb5.jar%2369!/:arclight-1.18.2-1.0.7-40114eb5]
        ... 21 more

**Comment by servicomcr** [comment]
[22:33:06 INFO] [GSit]: Enabling GSit v1.4.7
[22:33:06 ERROR] [STDERR]: java.sql.SQLException: No suitable driver found for jdbc:mysql://104.238.205.84:3306/
[22:33:06 ERROR] [STDERR]:      at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[22:33:06 ERROR] [STDERR]:      at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.manager.DManager.getConnection(DManager.java:53)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.manager.DManager.connect(DManager.java:40)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.connectDatabase(GSitMain.java:288)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.loadSettings(GSitMain.java:99)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.onEnable(GSitMain.java:171)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.handler$zgh000$arclight$enablePlugins(MinecraftServerMixin.java:2217)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:403)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:316)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:173)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261)
[22:33:06 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)
[22:33:06 ERROR] [STDERR]: java.sql.SQLException: No suitable driver found for jdbc:mysql://104.238.205.84:3306/s9115_sentarse
[22:33:06 ERROR] [STDERR]:      at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[22:33:06 ERROR] [STDERR]:      at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.manager.DManager.getConnection(DManager.java:53)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.manager.DManager.connect(DManager.java:42)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.connectDatabase(GSitMain.java:288)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.loadSettings(GSitMain.java:99)
[22:33:06 ERROR] [STDERR]:      at dev.geco.gsit.GSitMain.onEnable(GSitMain.java:171)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:264)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServerMixin.java:518)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/arclight@1.18.2-1.0.7-40114eb5/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServerMixin.java:432)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.handler$zgh000$arclight$enablePlugins(MinecraftServerMixin.java:2217)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServerMixin.java:403)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServerMixin.java:316)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServerMixin.java:173)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServerMixin.java:2099)
[22:33:06 ERROR] [STDERR]:      at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServerMixin.java:261)
[22:33:06 ERROR] [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Gecolay** [comment]
please share your plugin list

**Comment by servicomcr** [comment]
Yes SR

 AdvancedSpyInventory-2.4.jar
AureliumSkills-Beta1.3.21.jar
BetterRevive-v0.9.1-BETA.jar
BlockBall.jar
bloodmoon.jar
Brewery-3.1.1.jar
Clearlag.jar
DisableCommands-1.0.jar
EssentialsX-2.20.0.jar
GSit-1.4.7.jar
item-nbt-api-plugin-2.11.3.jar
LevelledMobs-3.10.3 b763.jar
LoginSecurity-3.1.1-Bukkit.jar
LuckPerms-Bukkit-5.4.88.jar
Multiverse-Core-4.3.1.jar
Multiverse-Portals-4.2.1.jar
PlaceholderAPI-2.11.3.jar
POG-1.8.jar
PowerBoard.jar
qstaffmode-core-1.3.6 (1).jar
SpigotPing_v3.0.jar
SuperVanish-6.2.16.jar
TreeFeller-1.22.0.jar
Vault.jar
WorldBorder.jar
worldedit-bukkit-7.2.12.jar

**Comment by Gecolay** [comment]
Looks like Arclight (which is based on Forge) comes with problems/changes in the data structure of entities.
There is nothing I could do with changes to GSit (except trying around and checking if every field is the way it should be) (way to much testing)
