### ISSUE TITLE
com.mysql.cj.jdbc.exceptions.CommunicationsException

### ISSUE THREAD

**Issue by d3adwolf** [Gecolay/GSit#121]
**Describe the bug**
There is a warning in the logs, but plugin seem to work fine.

**To Reproduce**
1. Start server core `pufferfish.jar`
2. Check logs
3. Logs:
```java [11:14:36] [Server thread/WARN]: com.mysql.cj.jdbc.exceptions.CommunicationsException: The last packet successfully received from the server was 80,570,698 milliseconds ago. The last packet sent successfully to the server was 80,570,699 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[11:14:36] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:175)
[11:14:36] [Server thread/WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
[11:14:36] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[11:14:36] [Server thread/WARN]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:972)
[11:14:36] [Server thread/WARN]: 	at GSit-1.5.0.jar//dev.geco.gsit.manager.DManager.executeAndGet(DManager.java:74)
[11:14:36] [Server thread/WARN]: 	at GSit-1.5.0.jar//dev.geco.gsit.manager.ToggleManager.canSit(ToggleManager.java:38)
[11:14:36] [Server thread/WARN]: 	at GSit-1.5.0.jar//dev.geco.gsit.events.InteractEvents.PIntE(InteractEvents.java:63)
[11:14:36] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unknown Source)
[11:14:36] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:14:36] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:14:36] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:14:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:14:36] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:14:36] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[11:14:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:593)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:537)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1908)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1326)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1303)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1296)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1274)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1162)
[11:14:36] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[11:14:36] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Full logs:**
[Pastebin](https://pastebin.com/CSXt9dKK)

**Additional context**
`git-Pufferfish-29 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 0ba7617 on HEAD)`

**Comment by Gecolay** [comment]
Tested with the latest GSit version (1.5.0) & the latest Pufferfish version. Can't reproduce.

**Comment by EmanYm** [comment]
@d3adwolf 
I'm not sure if you're still having this issue almost two months later.  I guess this could be left for prosperity reasons

I was was recently having this same issue, gSit would be blamed when someone joined and GriefPrevention would be blamed when they left the server.

It turns out it was an issue with Grief Prevention.
The solution is to add `?autoReconnect=true` to the end of the jsbc line in the GirefPrevention config.yml
Like this `URL: jdbc:mysql://<host>:3306/<database>?autoReconnect=true`
