### ISSUE TITLE
GSit seems to cause ticking world crash on dismount

### ISSUE THREAD

**Issue by kaweepatinn1** [gecolay/GSit#158]
I've had two crashes recently, both where the crash happened as soon as a player attempted to dismount another player. Both seem to have happened near water (one was in a boat, the other during swimming). The following is the error stack from the latest crash. Crash report is also attached.

[15:02:25] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1390) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:391) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:663) ~[fastutil-8.5.12.jar:?]
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1168) ~[fastutil-8.5.12.jar:?]
        at net.minecraft.server.level.PlayerChunkMap.l(PlayerChunkMap.java:1386) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:387) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:405) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1384) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
        ... 5 more
[crash-2024-05-19_15.02.25-server.txt](https://github.com/gecolay/GSit/files/15368819/crash-2024-05-19_15.02.25-server.txt)

**Comment by kaweepatinn1** [comment]
Version 1.9.1 on 1.20.4 server.

**Comment by gecolay** [comment]
I don't know why you report this error here. There is no GSit error or crash.

**Comment by kaweepatinn1** [comment]
I report this here because the crash only occurs on GSit dismount. I only experience this crash during a GSit dismount.
