### ISSUE TITLE
1.9.2 missing dependencies

### ISSUE THREAD

**Issue by BurkenDev** [gecolay/GSit#160]
Loading Gsit 1.9.2 in spigot 1.21 released today generates this error:

[19:54:35] [Server thread/ERROR]: net/kyori/adventure/text/serializer/json/JSONComponentSerializer initializing GSit v1.9.2 (Is it up to date?)
        at dev.geco.gsit.manager.mm.MPaperManager.<init>(MPaperManager.java:29) ~[?:?]
        at dev.geco.gsit.GSitMain.onLoad(GSitMain.java:148) ~[?:?]

**Comment by gecolay** [comment]
Please check if this is fixed for you with the latest Spigot 1.21 version & the latest GSit version 1.9.3
