### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by ZARAEM** [gecolay/GSit#163]
[16:22:20 WARN]: [GSit] Global task for GSit v1.9.3 generated an exception
java.lang.NoSuchMethodError: 'void net.minecraft.network.protocol.game.ClientboundAddEntityPacket.<init>(net.minecraft.world.entity.Entity)'
        at GSit-1.9.3.jar/dev.geco.gsit.mcv.v1_21_m.objects.GCrawl.lambda$tick$1(GCrawl.java:151) ~[GSit-1.9.3.jar:?]
        at GSit-1.9.3.jar/dev.geco.gsit.manager.TManager.lambda$run$1(TManager.java:48) ~[GSit-1.9.3.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[purpur-1.21.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[purpur-1.21.jar:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1692) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:507) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[purpur-1.21.jar:1.21-2235-778995d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2235-778995d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by gecolay** [comment]
Already fixed with https://github.com/gecolay/GSit/commit/0369441741a48d4d5f630ac5e860b6f173e9a6ef

**Comment by ZARAEM** [comment]
> Already fixed with [0369441](https://github.com/gecolay/GSit/commit/0369441741a48d4d5f630ac5e860b6f173e9a6ef)

is that in v 1.9.3 on spigot?
