### ISSUE TITLE
Task #31610 for GSit v1.0.5 generated an exception

### ISSUE THREAD

**Issue by Alexander397172YT** [Gecolay/GSit#19]
[17:27:20 INFO]: Killer_YT2021 issued server command: /crawl
[17:27:20 WARN]: [GSit] Task #31610 for GSit v1.0.5 generated an exception
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getBlock()" because "this.bloc" is null
        at dev.geco.gsit.mcv.v1_18_R1.objects.GCrawl.stop(GCrawl.java:180) ~[GSit-1.0.5.jar:?]
        at dev.geco.gsit.mcv.v1_18_R1.manager.CrawlManager.stopCrawl(CrawlManager.java:70) ~[GSit-1.0.5.jar:?]
        at dev.geco.gsit.mcv.v1_18_R1.objects.GCrawl$6.run(GCrawl.java:209) ~[GSit-1.0.5.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1574) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1497) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1502]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Gecolay** [comment]
Will be fixed with the next Update!
