### ISSUE TITLE
Folia issues: Cannot read field "captureTreeGeneration"

### ISSUE THREAD

**Issue by RitaSister** [gecolay/GSit#191]
[15:38:20] [Region shutdown thread/INFO]: [GSit] Disabling GSit v1.12.1
[15:38:20] [Region shutdown thread/ERROR]: Error occurred while disabling GSit v1.12.1
java.lang.NullPointerException: Cannot read field "captureTreeGeneration" because the return value of "net.minecraft.world.level.Level.getCurrentWorldData()" is null
	at net.minecraft.world.level.Level.getBlockState(Level.java:1311) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at org.bukkit.craftbukkit.block.CraftBlock.getType(CraftBlock.java:244) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at GSit-1.12.1.jar/dev.geco.gsit.manager.SitManager.removeSeat(SitManager.java:132) ~[GSit-1.12.1.jar:?]
	at GSit-1.12.1.jar/dev.geco.gsit.manager.SitManager.removeSeat(SitManager.java:119) ~[GSit-1.12.1.jar:?]
	at GSit-1.12.1.jar/dev.geco.gsit.manager.SitManager.clearSeats(SitManager.java:44) ~[GSit-1.12.1.jar:?]
	at GSit-1.12.1.jar/dev.geco.gsit.GSitMain.unload(GSitMain.java:178) ~[GSit-1.12.1.jar:?]
	at GSit-1.12.1.jar/dev.geco.gsit.GSitMain.onDisable(GSitMain.java:171) ~[GSit-1.12.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:161) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:97) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:541) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.disablePlugins(CraftServer.java:616) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:1098) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:856) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]
	at io.papermc.paper.threadedregions.RegionShutdownThread.run(RegionShutdownThread.java:135) ~[folia-1.21.1.jar:1.21.1-DEV-2e7bc07]

**Comment by gecolay** [comment]
Looks like a internal server error. GSit just uses "Block.getType()" which is a default method of Spigot/Paper.

**Comment by RitaSister** [comment]
> Looks like a internal server error. GSit just uses "Block.getType()" which is a default method of Spigot/Paper.

I read again this like "internal server error" but you don't understand I'm running on Folia and this not != Paper/Spigot. you can review [this](https://github.com/ArcanePlugins/LevelledMobs/issues/502) or [this](https://github.com/BreweryTeam/BreweryX/issues/70)
