### ISSUE TITLE
Update 1.18.2

### ISSUE THREAD

**Issue by CobaltBlue07** [Gecolay/GSit#29]
Please update to 1.18.2 version ty in advance

**Comment by sphings79** [comment]
```
<html>
<body>
<!--StartFragment-->

[14:46:07] [Server thread/ERROR]: Error occurred while enabling GSit v1.0.6 (Is it up to date?)
--
1085 | java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String, String)" because the return value of "dev.geco.gsit.GSitMain.getMessages()" is null
1086 | at dev.geco.gsit.manager.MManager.getRawMessage(MManager.java:49) ~[GSit-1.0.6.jar:?]
1087 | at dev.geco.gsit.manager.MManager.getMessage(MManager.java:46) ~[GSit-1.0.6.jar:?]
1088 | at dev.geco.gsit.manager.MManager.sendMessage(MManager.java:40) ~[GSit-1.0.6.jar:?]
1089 | at dev.geco.gsit.GSitMain.versionCheck(GSitMain.java:238) ~[GSit-1.0.6.jar:?]
1090 | at dev.geco.gsit.GSitMain.onEnable(GSitMain.java:158) ~[GSit-1.0.6.jar:?]
1091 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1092 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1093 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1094 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
1095 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
1096 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
1097 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
1098 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
1099 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
1100 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
1101 | at java.lang.Thread.run(Thread.java:833) ~[?:?]
  | 1 line
1103 | [14:46:07] [Server thread/ERROR]: Error occurred while disabling GSit v1.0.6 (Is it up to date?)
1104 | java.lang.NullPointerException: Cannot invoke "dev.geco.gsit.objects.ISitManager.clearSeats()" because the return value of "dev.geco.gsit.GSitMain.getSitManager()" is null
1105 | at dev.geco.gsit.GSitMain.onDisable(GSitMain.java:183) ~[GSit-1.0.6.jar:?]
1106 | at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1107 | at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1108 | at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1109 | at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1110 | at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
1111 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-220]
1112 | at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-220]
1113 | at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-220]
1114 | at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-220]
1115 | at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-220]
1116 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.18.2.jar:git-Paper-220]
1117 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
1118 | at java.lang.Thread.run(Thread.java:833) ~[?:?]

<!--EndFragment-->
</body>
</html>
```

**Comment by colaman90** [comment]
I got the same error like sphings79:

`[12:59:56] [Server thread/ERROR]: Error occurred while enabling GSit v1.0.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.getString(String, String)" because the return value of "dev.geco.gsit.GSitMain.getMessages()" is null
	at dev.geco.gsit.manager.MManager.getRawMessage(MManager.java:49) ~[GSit-1.0.6.jar:?]
	at dev.geco.gsit.manager.MManager.getMessage(MManager.java:46) ~[GSit-1.0.6.jar:?]
	at dev.geco.gsit.manager.MManager.sendMessage(MManager.java:40) ~[GSit-1.0.6.jar:?]
	at dev.geco.gsit.GSitMain.versionCheck(GSitMain.java:238) ~[GSit-1.0.6.jar:?]
	at dev.geco.gsit.GSitMain.onEnable(GSitMain.java:158) ~[GSit-1.0.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-231]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-231]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:59:56] [Server thread/INFO]: [GSit] Disabling GSit v1.0.6
[12:59:56] [Server thread/ERROR]: Error occurred while disabling GSit v1.0.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "dev.geco.gsit.objects.ISitManager.clearSeats()" because the return value of "dev.geco.gsit.GSitMain.getSitManager()" is null
	at dev.geco.gsit.GSitMain.onDisable(GSitMain.java:183) ~[GSit-1.0.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-231]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-231]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-231]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`
