### ISSUE TITLE
Unhandled exception executing command 'lay' in plugin GSit

### ISSUE THREAD

**Issue by mibby** [Gecolay/GSit#57]
GSit v1.2.1
Purpur dev 1735 (Paper 1.19)

```
[15:06:47] [Server thread/INFO]: mibby issued server command: /lay
[15:06:47] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'lay' in plugin GSit v1.2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2474) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2245) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.server.level.EntityPlayer.fy()'
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.createNPC(GPoseSeat.java:405) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.<init>(GPoseSeat.java:75) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:89) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:53) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.cmd.GLayCommand.onCommand(GLayCommand.java:114) ~[GSit-1.2.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more

**Comment by mibby** [comment]
Also occurs with spin & bellyflop.

```
[16:20:59] [Server thread/INFO]: mibby issued server command: /spin
[16:20:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'spin' in plugin GSit v1.2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2474) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2245) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.server.level.EntityPlayer.fy()'
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.createNPC(GPoseSeat.java:405) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.<init>(GPoseSeat.java:75) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:89) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:53) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.cmd.GSpinCommand.onCommand(GSpinCommand.java:114) ~[GSit-1.2.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more
```
```
[16:22:06] [Server thread/INFO]: mibby issued server command: /bellyflop
[16:22:06] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'bellyflop' in plugin GSit v1.2.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2474) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$19(ServerGamePacketListenerImpl.java:2245) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1386) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1363) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1356) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1334) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219) ~[purpur-1.19.jar:git-Purpur-1735]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:308) ~[purpur-1.19.jar:git-Purpur-1735]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'com.mojang.authlib.GameProfile net.minecraft.server.level.EntityPlayer.fy()'
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.createNPC(GPoseSeat.java:405) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.objects.GPoseSeat.<init>(GPoseSeat.java:75) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:89) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.mcv.v1_19_R1_2.manager.PoseManager.createPose(PoseManager.java:53) ~[GSit-1.2.1.jar:?]
	at dev.geco.gsit.cmd.GBellyFlopCommand.onCommand(GBellyFlopCommand.java:114) ~[GSit-1.2.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
	... 17 more
```

**Comment by Gecolay** [comment]
Fixed. Please redownload the latest version from spigot!

**Comment by mibby** [comment]
Confirmed fixed, thanks.
