### ISSUE TITLE
sit problem

### ISSUE THREAD

**Issue by twseer67875** [Gecolay/GSit#70]
On my server if I try to sit I get this error and can't sit

```
[00:35:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sit' in plugin GSit v1.2.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-177]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-177]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2293) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2247) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchFieldError: P
	at dev.geco.gsit.mcv.v1_19_R1_2.util.SpawnUtil.createSeatEntity(SpawnUtil.java:25) ~[GSit-1.2.5.jar:?]
	at dev.geco.gsit.manager.SitManager.createSeat(SitManager.java:87) ~[GSit-1.2.5.jar:?]
	at dev.geco.gsit.util.SitUtil.createSeatForStair(SitUtil.java:49) ~[GSit-1.2.5.jar:?]
	at dev.geco.gsit.cmd.GSitCommand.onCommand(GSitCommand.java:107) ~[GSit-1.2.5.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

```
How to reproduce
Use /sit to try to sit and that's it
```

```
Server Version:
This server is running Paper version git-Paper-177 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 1bbd273)
```

```
Plugins (70): AntiMapCopy, AuxProtect, BBeeChecker, BetterRTP, BlockLocker, ChatControlRed, ChatPreview, ChestSort, Chunky, ChunkyBorder, CoCoBeenAgreeRulesPlugin, CoCoBeenAutoRestartPlugin, CoCoBeenBanFromClaim, CoCoBeenBarrierBlockPlugin, CoCoBeenBossBarHealth, CoCoBeenDisplayAxolotlBucket, CoCoBeenDragonEggRespawn, CoCoBeenGriefPreventionTeleport, CoCoBeenHPETParticles, CoCoBeenPlaceholderPlugin, CoCoBeenPlayerDeathSkullDrop, CoCoBeenPlayerSignItem, CoCoBeenServerTweaks, CoCoBeenShulkerBoxInvsee, ColoredAnvils, CoreProtect, CoreProtectTNT, DeluxeMenus, DiscordSRV, Elevator, EntityMoneyDrop, Essentials, EssentialsSpawn, FarmControl, GriefPrevention, GriefPreventionTempFly, GriefPreventionTweaks, GSit, HeadDatabase, HolographicDisplays, HPET, InteractiveChat, InvisibleItemFrames, LuckPerms, MapSyncTweaks, MarketPlace, MaSuiteCore, MaSuiteTeleports, Minepacks, MysqlPlayerDataBridge, NBTAPI, NoEncryption, OreReplacer, PlaceholderAPI, PlayerParticles, PlayerWarps, PlugManX (PlugMan), ProtocolLib, PureLandCheque, PvPManager, QuickShop, QuickShopBank, SafariNet, spark, SyncStaticMapView, TAB-Bridge, UltimateTimber, Vault, Vulcan, WorldEdit
```

**Comment by Gecolay** [comment]
Use the latest version of GSit and it will work!
