### ISSUE TITLE
Player cannot stand up

### ISSUE THREAD

**Issue by KioProject123** [Gecolay/GSit#93]
I don't know how this happened. Some players can't stand up after crawling.
It is not clear how it is triggered, but this situation has existed on my server for a long time.
```
[Server thread/ERROR]: Could not pass event PlayerToggleSneakEvent to GSit v1.3.6
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.plugin.RegisteredListener.getListener()" is null
	at org.bukkit.event.HandlerList.unregister(HandlerList.java:180) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.event.HandlerList.unregisterAll(HandlerList.java:93) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at dev.geco.gsit.mcv.v1_19_R2.objects.GCrawl.stop(GCrawl.java:181) ~[GSit-1.3.6.jar:?]
	at dev.geco.gsit.manager.CrawlManager.stopCrawl(CrawlManager.java:86) ~[GSit-1.3.6.jar:?]
	at dev.geco.gsit.mcv.v1_19_R2.objects.GCrawl$3.PTogSE(GCrawl.java:91) ~[GSit-1.3.6.jar:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:git-petal-"08825ff"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[petal-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2719) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:197) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1473) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[petal-1.19.3.jar:git-petal-"08825ff"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Gecolay** [comment]
Look like this are caused by internal problems from your server type "petal" you should use "paper" or a fork of "paper".
