### ISSUE TITLE
java.sql.SQLException: No suitable driver found

### ISSUE THREAD

**Issue by mtmustski** [Gecolay/GSit#97]
Using GSit v1.4.0, I get a SQL exception when starting the server.

```
[13:37:21] [Server thread/WARN]: java.sql.SQLException: No suitable driver found for jdbc:sqlite:plugins/GSit/data/data.db
[13:37:21] [Server thread/WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:706)
[13:37:21] [Server thread/WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:252)
[13:37:21] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.manager.DManager.getConnection(DManager.java:54)
[13:37:21] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.manager.DManager.connect(DManager.java:31)
[13:37:21] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.GSitMain.loadSettings(GSitMain.java:94)
[13:37:21] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.GSitMain.onEnable(GSitMain.java:171)
[13:37:21] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[13:37:21] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceM$
[13:37:21] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.j$
[13:37:21] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[13:37:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[13:37:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[13:37:21] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
[13:37:21] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[13:37:21] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[13:37:21] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[13:37:21] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:37:21] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[13:37:21] [Server thread/INFO]: [GSit] The plugin was successfully enabled.
```

My server is running `paper-1.19.4-458` which is marked experimental so that could be part of it.  Running `java --version` returns:
```
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

Additionally, when I try sitting on something it creates an armor stand under my player and generates the following error in the console.
```
[13:42:00] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.next()" because "resultSet" is null
[13:42:00] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.manager.ToggleManager.canSit(ToggleManager.java:23)
[13:42:00] [Server thread/WARN]:        at GSit-1.4.0.jar//dev.geco.gsit.events.InteractEvents.PIntE(InteractEvents.java:47)
[13:42:00] [Server thread/WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor103.execute(Unkno$
[13:42:00] [Server thread/WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[13:42:00] [Server thread/WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:42:00] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:42:00] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:42:00] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java$
[13:42:00] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:42:00] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFa$
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:528)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1949)
[13:42:00] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[13:42:00] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:9)
[13:42:00] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(Play$
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:42:00] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:42:00] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[13:42:00] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1318)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[13:42:00] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[13:42:00] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:42:00] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

Looks like either the plugin is missing the JDBC SQLite driver, or my Java version is outdated and doesn't have the driver.  I've configured my other plugins to use MySQL / mariadb to store data.  Does your plugin support MySQL, or just SQLite?

**Comment by Gecolay** [comment]
It supports MySQL, take a look in the data folder there is the "data.yml" file to change it. Which Java version do you use?

**Comment by mtmustski** [comment]
Changing the database to MySQL fixed the SQL exception errors in the console.  It no longer throws any errors in the console when I sit in game either which makes sense.  However my player is still shown sitting on top of an armor stand.

I'm using ViaVersion / ViaBackwards to allow anyone from 1.19 to connect to the server.  I connected on 1.19.3 and the server is on 1.19.4.  I wonder if this is contributing to the armor stand issue.  I can test some more on my own time unless you have any ideas?  Either way, connecting to MySQL fixes my SQL driver issue, thanks for the suggestion!

**Comment by Gecolay** [comment]
Fixed
